
Stages = {
    'registration':
        (),
    'log_in':
        (
            'identification',
            'authentication',
            #тут можно придумать двухфакторную аутентификацию с вводом имени любой темы
            'authorisation'
        ),
    'add_topic':
        (
            'add_name',
            'add_chapter',
            'add_note',
            'add_question',
            'add_answer',
        ),
    'change_topic':
        (
            'change_name',
            'change_chapter',
            'change_note',
            'change_question',
            'change_answer',
            'split_topic',
            'delete_topic'
        ),
    'print_list_of_topics':
        (
            'to_repeat',
            'in_chapter',
        ),
    'choice_topic_to_repeat':
        (
            'by_name',
            'random',
            'first',
            'first_by_chapter'
        ),
    'repeat_topic':
        (
            'print_answers',
            'record',
            'cancel',
            'delete_topic'
        ),
    'add_chapter':
        (
            'add_name',
            'add_description'
        ),
    'change_chapter':
        (
            'change_name',
            'change_description',
            'join_chapters',
            'delete_chapter'
        ),
    'print_list_of_chapters':
        (
            'all',
            'to_repeat'
        )
}

class Automat:
    pass